apiVersion: v1
kind: ConfigMap

metadata:
  name: nginx-config
  namespace: fil-rouge-devops

data:
  default.conf: |
    server {
      listen 80;

      location / {
        proxy_pass http://fil-rouge-devops:80;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }
    }