name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"

  pull_request:
    branches:
      - main
      - develop

jobs:
  docker:
    uses: ./.github/workflows/reusable-docker.yml